app:
  name: duni-deployment

replicaCount: 1

image:
  repository: muhammedsinanust/duniversity
  tag: latest
  pullPolicy: Always

port:
  container: 3000

mysql:
  name: mysql-deployment
  replicas: 1
  image: mysql
  tag: 8.0
  imagePullPolicy: IfNotPresent
  port: 3306